# Generated by Django 3.1.3 on 2021-08-05 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('redhunt', '0002_auto_20210805_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='org',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='redhunt.organisation'),
        ),
    ]
