# Generated by Django 3.1.3 on 2021-08-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redhunt', '0003_auto_20210805_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='email',
            field=models.EmailField(default='#', max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
